custom:
  - https://www.paypal.com/donate/?business=GAFAK6UR9XJE8&no_recurring=0&item_name=Support+this+unofficial+fan+project+with+assets%2C+tools%2C+software%2C+hosting+and+other+development+costs.&currency_code=AUD
